export const initialMovements = [
  {
    id: 'm1',
    date: '2026-09-02',
    account: 'CREDICOOP',
    folder: 'Aportes',
    concept: 'INGRESOS POR SERVICIOS',
    detail: 'Cobro de servicio institucional',
    operation: 'OP-1001',
    income: 4200000,
    expense: 0,
    invoice: 'FC-DEMO-001',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm2',
    date: '2026-09-04',
    account: 'MERCADO LIBRE 2',
    folder: 'Administración',
    concept: 'ALQUILERES INSTALACIONES',
    detail: 'Alquiler mensual',
    operation: 'OP-1002',
    income: 0,
    expense: 980000,
    invoice: '',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm3',
    date: '2026-09-08',
    account: 'CREDICOOP',
    folder: 'Servicios',
    concept: 'SALARIOS Y PAGOS ESPECIALISTAS',
    detail: 'Pago de especialistas',
    operation: 'OP-1003',
    income: 0,
    expense: 1350000,
    invoice: '',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm4',
    date: '2026-09-12',
    account: 'MERCADO LIBRE',
    folder: 'Socios',
    concept: 'CUOTAS SOCIALES',
    detail: 'Cuotas sociales del período',
    operation: 'OP-1004',
    income: 275000,
    expense: 0,
    invoice: '',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm5',
    date: '2026-09-18',
    account: 'CREDICOOP',
    folder: 'Banco',
    concept: 'CARGO BANCO',
    detail: 'Comisiones bancarias',
    operation: 'OP-1005',
    income: 0,
    expense: 68500,
    invoice: '',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm6',
    date: '2026-10-01',
    account: 'CREDICOOP',
    folder: 'Servicios',
    concept: 'INGRESOS POR SERVICIOS',
    detail: 'Acreditación de servicio',
    operation: 'OP-1006',
    income: 5100000,
    expense: 0,
    invoice: 'FC-DEMO-002',
    notes: 'Dato demostrativo',
  },
  {
    id: 'm7',
    date: '2026-10-02',
    account: 'MERCADO LIBRE 2',
    folder: 'Administración',
    concept: 'SERVICIOS',
    detail: 'Servicios y conectividad',
    operation: 'OP-1007',
    income: 0,
    expense: 310000,
    invoice: '',
    notes: 'Dato demostrativo',
  },
];

export const initialHours = [
  {
    id: 'h1',
    date: '2026-09-03',
    specialist: 'Especialista A',
    service: 'PAE - Servicio RRHH',
    hours: 8,
    hourlyRate: 30000,
    notes: 'Jornada demostrativa',
  },
  {
    id: 'h2',
    date: '2026-09-05',
    specialist: 'Especialista B',
    service: 'PAE - Energía',
    hours: 6,
    hourlyRate: 30000,
    notes: 'Jornada demostrativa',
  },
  {
    id: 'h3',
    date: '2026-09-10',
    specialist: 'Especialista A',
    service: 'PAE - Servicio RRHH',
    hours: 7.5,
    hourlyRate: 30000,
    notes: 'Jornada demostrativa',
  },
  {
    id: 'h4',
    date: '2026-10-01',
    specialist: 'Especialista C',
    service: 'UNPSJB',
    hours: 5,
    hourlyRate: 30000,
    notes: 'Jornada demostrativa',
  },
];

export const initialReceivables = [
  { id: 'r1', dueDate: '2026-10-24', description: 'Cobro futuro demo', amount: 1800000 },
  { id: 'r2', dueDate: '2026-10-27', description: 'Acreditación demo', amount: 950000 },
];

export const accounts = [
  'CREDICOOP',
  'MERCADO LIBRE',
  'MERCADO LIBRE 2',
  'EFECTIVO',
  'PREX',
  'PERSONAL PAY',
];
